# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11a1cTD2qL256wHo05RaJHmNx8BxUa0sU

# **Importing the neccessary libraries:**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import json
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, root_mean_squared_error
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.ensemble import RandomForestRegressor
plt.style.use("ggplot")

import warnings
warnings.filterwarnings("ignore")

# %matplotlib inline

"""# Step 1: Reading the dataset and checking what all features are present


## Target ---> CO2 Emissions(g/km)

*   Checking for if any Nulls values.
*   Evaluating if there are duplicate (If yes dropping them)











"""

data = pd.read_csv("/Users/poojaborana/Desktop/DataScience/CO_Emission/CO2_Emissions_Canada.csv")
data.head()

data.info()

print('Fuel Types    : ', data['Fuel Type'].unique())
print('Cylinders     : ', data['Cylinders'].unique())
print('Vehicle Class : ', data['Vehicle Class'].unique())
print('Transmission  : ', data['Transmission'].unique())

data.duplicated().sum()

data.drop_duplicates(inplace = True)

data.duplicated().sum()

data.isnull().sum()

"""# Step 2:  Data Exploratory Analysis (EDA):

*   ### Ploting few features againt the target in order to understand how each feature is influence the target.
*  ### Correlation




"""

plt.figure(figsize = (20,8), dpi = 200)
sns.scatterplot(data = data, x = 'Engine Size(L)', y = 'CO2 Emissions(g/km)')
plt.show()

plt.figure(figsize = (20,8), dpi = 200)
sns.scatterplot(data = data, x = 'Fuel Consumption Comb (L/100 km)', y = 'CO2 Emissions(g/km)')
plt.show()

plt.figure(figsize = (20, 10), dpi = 200)
plt.subplot(1,2,1)
sns.barplot(data = data, x = 'Cylinders', y = 'CO2 Emissions(g/km)')
plt.subplot(1,2,2)
sns.boxplot(data = data, x = 'Cylinders', y = 'CO2 Emissions(g/km)')

plt.figure(figsize = (16,5), dpi = 200)
plt.subplot(1,2,1)
sns.barplot( x = 'Fuel Type', y = 'CO2 Emissions(g/km)', data = data)
plt.subplot(1,2,2)
sns.boxplot(x = 'Fuel Type', y ='CO2 Emissions(g/km)', data = data)

data.groupby('Fuel Type')['CO2 Emissions(g/km)'].mean()

data_desc = data.groupby('Transmission')['CO2 Emissions(g/km)'].mean().sort_values(ascending = False).index
plt.figure(figsize = (16,5), dpi = 200)
sns.barplot(data = data, order =  data_desc , y = 'Transmission', x = 'CO2 Emissions(g/km)')
plt.show()

desc_order = data.groupby('Vehicle Class')['CO2 Emissions(g/km)'].mean().sort_values(ascending = False).index
plt.figure(figsize = (16,8), dpi = 200)
sns.barplot(x = 'CO2 Emissions(g/km)', y = 'Vehicle Class',  data = data, order = desc_order)

# Checking Correlation  (Multicollinearity)
cols = ['Engine Size(L)', 'Fuel Consumption City (L/100 km)','Fuel Consumption Hwy (L/100 km)','Fuel Consumption Comb (L/100 km)','Fuel Consumption Comb (mpg)','CO2 Emissions(g/km)']
plt.figure(figsize = (12,6), dpi = 200)
sns.heatmap(data[cols].corr(), annot = True)

"""# Step 3: Separating the feature and Target, and spliting into train and test sets"""

cols = ['Vehicle Class', 'Fuel Type', 'Transmission', 'Cylinders', 'Engine Size(L)', 'Fuel Consumption Comb (L/100 km)']
X = data[cols]
Y = data[['CO2 Emissions(g/km)']]

print('Independent Feature Set Shape : ', X.shape)
print('Dependent Feature Shape       : ', Y.shape)

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 29)

print('Training data shape   : ', x_train.shape)
print('Training labels shape : ', y_train.shape)
print('Testing data shape    : ', x_test.shape)
print('Testing labels shape  : ', y_test.shape)

"""# Step 4: Feature Engineering:

*   ### **Scaling**  : MinMaxScaler --> Numerical columns
*   ### **Encoding** : OrdinalEncoding --> Categorical columns


"""

cols = ['Engine Size(L)','Fuel Consumption Comb (L/100 km)']

scaler = MinMaxScaler()
scaler.fit(x_train[cols])

x_train[cols] = scaler.transform(x_train[cols])
x_test[cols] = scaler.transform(x_test[cols])

cols = ['Vehicle Class', 'Fuel Type', 'Transmission']
encoder = OrdinalEncoder()

# Fit on the training set
encoder.fit(x_train[cols])

# Transforming training and test sets
x_train[cols] = encoder.transform(x_train[cols])
x_test[cols] = encoder.transform(x_test[cols])

"""# Step 5: Training and Evaluating the Models:

1.   **KneighborsRegressor**
2.   **LinearRegression**

1.   **Regularization**: <br>      1. Lasso (L1 Regularization) <br>   2. Ridge (L2 Regularization) <br>    3.ElasticNet

1.   **RandomForestRegressor**

# KneighborsRegressor
"""

regressor = KNeighborsRegressor(n_neighbors= 3)
regressor.fit(x_train, y_train)

regressor.predict(x_test[0:5])

pred_train = regressor.predict(x_train)
pred_test = regressor.predict(x_test)

print('Training set score : ', r2_score(y_train, pred_train))
print('testing set score :  ', r2_score(y_test, pred_test))

"""# LinearRegression"""

regression = LinearRegression()
regression.fit(x_train, y_train)

pred_train = regression.predict(x_train)
pred_test  = regression.predict(x_test)

print('Linearregression training set score  : ', r2_score(y_train,pred_train))
print('Linearregression test set score      : ', r2_score(y_test, pred_test))

# MAE
MAE = mean_absolute_error(y_test, pred_test)
print("Mean absolute error    : ", MAE)

# MSE
MSE = mean_squared_error(y_test, pred_test)
print("Mean squared error    : ", MSE)

# RMSE
RMSE = root_mean_squared_error(y_test, pred_test)
print("Mean squared error    : ", RMSE)

"""# Regularized regresion Models
- Used to control overfitting
- Works by applying a penalty on the cost function
<br>

- 1. Lasso (L1 Regularization)
- 2. Ridge (L2 Regularization)

<img align = 'left' src = 'regularization.png' style = 'width:400px; hieght:150px' />
"""

regressor = Lasso(alpha = 1)                                                          # Regression with L1 Regularization
                                                                                      # alpha : regularization parameter
regressor.fit(x_train, y_train)

print('Training set score : ', regressor.score(x_train, y_train))
print('Testing set score  : ', regressor.score(x_test, y_test))

# Regression with L2 Regularization
regressor = Ridge(alpha = 1)
regressor.fit(x_train, y_train)

print('Training set score : ', regressor.score(x_train, y_train))
print('Testing set score  : ', regressor.score(x_test, y_test))

# Regression with L1 and L2 Regularization
regressor = ElasticNet(alpha = 1)
regressor.fit(x_train, y_train)

print('Training set score : ', regressor.score(x_train, y_train))
print('Testing set score  : ', regressor.score(x_test, y_test))

"""# Random Forest
RandomForestRegressor(
>     bootstrap=True, class_weight=None, criterion='squared_error',
      max_depth=10, max_features='auto', max_leaf_nodes=None,
      min_impurity_decrease=0.0, min_impurity_split=None,
      min_samples_leaf=1, min_samples_split=2,
      min_weight_fraction_leaf=0.0, n_estimators=10,
      n_jobs=None, oob_score=False, random_state=14,verbose=0,
      warm_start=False)
"""

regressor = RandomForestRegressor(n_estimators= 15, max_features = 5)
regressor.fit(x_train, y_train)

print('Training Set Score : ', regressor.score(x_train, y_train))
print('Testing Set Score  : ', regressor.score(x_test, y_test))

"""# Step 6 : Hyperparameter Tuning

1.  GridSearchCV
2.  RandomizedSearchCV





"""

search_params = {
    'n_estimators' : [10, 20, 30, 40, 50],
    'max_depth'    : [3, 4, 6, 8, 10],
    'max_features' : [3, 4, 5, 6]
}

"""# **GridSearchCV**"""

grid_search = GridSearchCV(estimator = regressor,
                           param_grid = search_params,
                           scoring = ['r2'],
                           cv = 5,
                           refit = 'r2',
                           verbose = 1)

grid_search.fit(x_train, y_train)

grid_search.best_params_

grid_search.best_score_

best_model = grid_search.best_estimator_
best_model

grid_search.cv_results_

df = pd.DataFrame(grid_search.cv_results_).sort_values('mean_test_r2', ascending = False)
df.head()

df.to_csv('GridSearchResults.csv')

"""# RandomizedSearchCV"""

search_params = {
    'n_estimators' : [10, 20, 30, 40, 50],
    'max_depth'    : [3, 4, 6, 8, 10],
    'max_features' : [3, 4, 5, 6]
}

randomized_search = RandomizedSearchCV(estimator = regressor,
                                       param_distributions = search_params,
                                       scoring = ['r2'],
                                       cv = 5,
                                       refit = 'r2',
                                       n_iter = 10,
                                       verbose = 3)

randomized_search.fit(x_train, y_train)

randomized_search.best_params_

randomized_search.best_score_

best_model = randomized_search.best_estimator_
best_model

df2 = pd.DataFrame(randomized_search.cv_results_).sort_values('mean_test_r2', ascending = False)
df2.head()

df2.to_csv('RandomizedSearchResult.csv')

"""# Considering efficiency the best model after considering efficiency:"""

best_model = RandomForestRegressor(max_depth = 6, n_estimators = 30, max_features = 4)
best_model.fit(x_train, y_train)

print('Training Set Score : ', best_model.score(x_train, y_train))
print('Testing Set Score  : ', best_model.score(x_test, y_test))


# 1. Save the best model
joblib.dump(best_model, "model.joblib")

# 2. Save the scaler
joblib.dump(scaler, "scaler.joblib")

# 3. Save the encoder
joblib.dump(encoder, "encoder.joblib")

# 4. Save unique values for dropdowns in Streamlit app
categories = {
    "Vehicle Class": sorted(data['Vehicle Class'].unique().tolist()),
    "Fuel Type": sorted(data['Fuel Type'].unique().tolist()),
    "Transmission": sorted(data['Transmission'].unique().tolist()),
    "Cylinders": sorted(data['Cylinders'].unique().tolist())
}
with open("categories.json", "w") as f:
    json.dump(categories, f)

print("✅ All files saved!")
print("Files: model.joblib, scaler.joblib, encoder.joblib, categories.json")